### ISSUE TITLE
Combined selecors not working (can be hacked)

### ISSUE THREAD

**Issue by jakob-e** [marcj/css-element-queries#33]
If you want to apply a style based on multiple conditions like:

````SCSS
.eq[min-width~="300px"][max-width~="600px"] { background: magenta; };
````

It is only possible if you add the rules individually (must be added before and must have content). 
````SCSS
.eq[min-width~="300px"], 
.eq[max-width~="600px"]{/**/} /* Does nothing – but make combined selectors work */
.eq[min-width~="300px"][max-width~="600px"] { background: magenta; };
````

It would be nice if this could be avoided :- )

**PS** I wrote this little mixin to auto generate the hack:

````SCSS
@mixin eq($min-width:null, $max-width:null, $min-height:null, $max-height:null){
  $eq:'';
  $eq:$eq + if($min-width,  '[min-width~="#{$min-width}"]', '');
  $eq:$eq + if($max-width,  '[max-width~="#{$max-width}"]', '');
  $eq:$eq + if($min-height, '[min-height~="#{$min-height}"]', '');
  $eq:$eq + if($max-height, '[max-height~="#{$max-height}"]', '');
  // --- Start hack ----
  @if $min-width  and ($max-width or $min-height or $max-height) { 
    &[min-width~="#{$min-width}"]  { /**/ }; 
  }    
  @if $max-width  and ($min-width or $min-height or $max-height) { 
    &[max-width~="#{$max-width}"]  { /**/ }; 
  } 
  @if $min-height and ($min-width or $max-width or $max-height)  { 
    &[min-height~="#{$min-height}"]{ /**/ };
  }  
  @if $max-height and ($min-width or $max-width or $min-height)  { 
    &[max-height~="#{$max-height}"]{ /**/ };
  }           
  // --- End hack ----
  &#{$eq} { @content; }
}


// Combined selectors
.eq { 
  @include eq($min-width: 200px, $max-width: 600px, $min-height: 70px, $max-height: 80px){
    background:red;
  }
}

// Output CSS
.eq[min-width~="200px"] { /**/ } 
.eq[max-width~="600px"] { /**/ }
.eq[min-height~="70px"] { /**/ }
.eq[max-height~="80px"] { /**/ }
.eq[min-width~="200px"][max-width~="600px"][min-height~="70px"][max-height~="80px"] {
  background: red;
}


// Single selector
.eq { 
  @include eq($max-width: 600px){
    background:red;
  }
}

// Output CSS (no hack needed)
.eq[max-width~="600px"] {
  background: red;
}


````
