### ISSUE TITLE
Not quite pixel perfect.

### ISSUE THREAD

**Issue by jehoshua02** [marcj/css-element-queries#35]
These are my styles:

```scss
@mixin small {
  &[max-width~="400px"] {
    @content;
  }
}

@mixin medium {
  &[min-width~="400px"] {
    @content;
  }
}

@mixin large {
  &[min-width~="600px"] {
    @content;
  }
}

.responsive-color {
  color: white;
  background-color: brown;

  @include small {
    background-color: red;
  }

  @include medium {
    background-color: orange;
  }

  @include large {
    background-color: green;
  }
}
```

I observe the following as I adjust the width of the element:

+ Starting at `599px` and ticking up to `600px`, the color changes from orange to green as expected.
+ Then going back down to `599px`, the color stays green when expecting orange.
+ Then going down one more pixel to `598px` the color changes to orange.
+ Starting at `598px` and going back up to `600px` the color changes back to green as expected.
