### ISSUE TITLE
OSX rendering bug: scrollbar fragments

### ISSUE THREAD

**Issue by sgruenholz** [marcj/css-element-queries#63]
I've encountered an OSX version specific rendering bug where the resize sensors intermittently show visible scrollbars while the page is loading/rendering and leave behind residual fragments.

![scrollbar-fragments](https://cloud.githubusercontent.com/assets/8251045/9883340/6d3e641a-5b8e-11e5-8522-e44af2bc1c0e.png)

OSX 10.9.5 - does not occur in any browser
OSX 10.10.3 - reproduced in both Chrome 45.0.2454.85 and Safari 8.0.8

I was able to prevent this by setting overflow: hidden (instead of auto) on all the resize sensors. This prevents the intermittent scrollbars from rendering while still allowing the functionality of the sensors to work.

For now, I put in a css hack to stop the customer from freaking out, but it would be better to just use overflow: hidden in the inline styles (assuming there are no unintended consequences).

```css
<style>
/* fix for OSX version specific scrollbar rendering bug */
.resize-sensor,
.resize-sensor-expand,
.resize-sensor-shrink {
  overflow: hidden !important;
}
</style>
```

Let me know if you want me to do a pull request.
