### ISSUE TITLE
Not work on CSS Media Queries

### ISSUE THREAD

**Issue by Foolyou** [marcj/css-element-queries#97]
Given an element with these CSS rules:

```css
#element {
      display: block;
      width: 60%;
    }
    @media (max-width: 600px) {
      #element {
        display: none;
      }
}
```

If width of the viewport change from `> 600px` to `< 600px`, the sensor runs well. But if we make the viewport change from `< 600px` to `> 600px`, the sensor cannot sense element width changing.
